version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_LIVEKIT_URL=${NEXT_PUBLIC_LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    depends_on:
      - agent

  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    expose:
      - "8000"
    environment:
      - PORT=8000
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}

networks:
  default:
    name: ahoum-agent-net
